// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ghmock

import (
	"sync"

	"github.com/cli/cli/v2/internal/gh"
)

// Ensure, that TokenRefresherMock does implement gh.TokenRefresher.
// If this is not the case, regenerate this file with moq.
var _ gh.TokenRefresher = &TokenRefresherMock{}

// TokenRefresherMock is a mock implementation of gh.TokenRefresher.
//
//	func TestSomethingThatUsesTokenRefresher(t *testing.T) {
//
//		// make and configure a mocked gh.TokenRefresher
//		mockedTokenRefresher := &TokenRefresherMock{
//			RefreshFunc: func(refreshToken string, hostname string) (gh.RefreshableCredential, error) {
//				panic("mock out the Refresh method")
//			},
//		}
//
//		// use mockedTokenRefresher in code that requires gh.TokenRefresher
//		// and then make assertions.
//
//	}
type TokenRefresherMock struct {
	// RefreshFunc mocks the Refresh method.
	RefreshFunc func(refreshToken string, hostname string) (gh.RefreshableCredential, error)

	// calls tracks calls to the methods.
	calls struct {
		// Refresh holds details about calls to the Refresh method.
		Refresh []struct {
			// RefreshToken is the refreshToken argument value.
			RefreshToken string
			// Hostname is the hostname argument value.
			Hostname string
		}
	}
	lockRefresh sync.RWMutex
}

// Refresh calls RefreshFunc.
func (mock *TokenRefresherMock) Refresh(refreshToken string, hostname string) (gh.RefreshableCredential, error) {
	if mock.RefreshFunc == nil {
		panic("TokenRefresherMock.RefreshFunc: method is nil but TokenRefresher.Refresh was just called")
	}
	callInfo := struct {
		RefreshToken string
		Hostname     string
	}{
		RefreshToken: refreshToken,
		Hostname:     hostname,
	}
	mock.lockRefresh.Lock()
	mock.calls.Refresh = append(mock.calls.Refresh, callInfo)
	mock.lockRefresh.Unlock()
	return mock.RefreshFunc(refreshToken, hostname)
}

// RefreshCalls gets all the calls that were made to Refresh.
// Check the length with:
//
//	len(mockedTokenRefresher.RefreshCalls())
func (mock *TokenRefresherMock) RefreshCalls() []struct {
	RefreshToken string
	Hostname     string
} {
	var calls []struct {
		RefreshToken string
		Hostname     string
	}
	mock.lockRefresh.RLock()
	calls = mock.calls.Refresh
	mock.lockRefresh.RUnlock()

	return calls
}
