// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package client

import (
	"github.com/cli/cli/v2/internal/ghrepo"
	"sync"
)

// Ensure, that ArtifactClientMock does implement ArtifactClient.
// If this is not the case, regenerate this file with moq.
var _ ArtifactClient = &ArtifactClientMock{}

// ArtifactClientMock is a mock implementation of ArtifactClient.
//
//	func TestSomethingThatUsesArtifactClient(t *testing.T) {
//
//		// make and configure a mocked ArtifactClient
//		mockedArtifactClient := &ArtifactClientMock{
//			CreateFunc: func(repo ghrepo.Interface, issueNumber int, artifactType string, name string, body string) (*Artifact, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(repo ghrepo.Interface, issueNumber int, number int) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(repo ghrepo.Interface, issueNumber int, number int) (*ArtifactWithVersions, error) {
//				panic("mock out the Get method")
//			},
//			IsPullRequestFunc: func(repo ghrepo.Interface, number int) (bool, error) {
//				panic("mock out the IsPullRequest method")
//			},
//			ListFunc: func(repo ghrepo.Interface, issueNumber int, artifactType string, limit int) ([]Artifact, error) {
//				panic("mock out the List method")
//			},
//			UploadTargetFunc: func(repo ghrepo.Interface, number int) (*UploadTarget, error) {
//				panic("mock out the UploadTarget method")
//			},
//		}
//
//		// use mockedArtifactClient in code that requires ArtifactClient
//		// and then make assertions.
//
//	}
type ArtifactClientMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(repo ghrepo.Interface, issueNumber int, artifactType string, name string, body string) (*Artifact, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(repo ghrepo.Interface, issueNumber int, number int) error

	// GetFunc mocks the Get method.
	GetFunc func(repo ghrepo.Interface, issueNumber int, number int) (*ArtifactWithVersions, error)

	// IsPullRequestFunc mocks the IsPullRequest method.
	IsPullRequestFunc func(repo ghrepo.Interface, number int) (bool, error)

	// ListFunc mocks the List method.
	ListFunc func(repo ghrepo.Interface, issueNumber int, artifactType string, limit int) ([]Artifact, error)

	// UploadTargetFunc mocks the UploadTarget method.
	UploadTargetFunc func(repo ghrepo.Interface, number int) (*UploadTarget, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Repo is the repo argument value.
			Repo ghrepo.Interface
			// IssueNumber is the issueNumber argument value.
			IssueNumber int
			// ArtifactType is the artifactType argument value.
			ArtifactType string
			// Name is the name argument value.
			Name string
			// Body is the body argument value.
			Body string
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Repo is the repo argument value.
			Repo ghrepo.Interface
			// IssueNumber is the issueNumber argument value.
			IssueNumber int
			// Number is the number argument value.
			Number int
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Repo is the repo argument value.
			Repo ghrepo.Interface
			// IssueNumber is the issueNumber argument value.
			IssueNumber int
			// Number is the number argument value.
			Number int
		}
		// IsPullRequest holds details about calls to the IsPullRequest method.
		IsPullRequest []struct {
			// Repo is the repo argument value.
			Repo ghrepo.Interface
			// Number is the number argument value.
			Number int
		}
		// List holds details about calls to the List method.
		List []struct {
			// Repo is the repo argument value.
			Repo ghrepo.Interface
			// IssueNumber is the issueNumber argument value.
			IssueNumber int
			// ArtifactType is the artifactType argument value.
			ArtifactType string
			// Limit is the limit argument value.
			Limit int
		}
		// UploadTarget holds details about calls to the UploadTarget method.
		UploadTarget []struct {
			// Repo is the repo argument value.
			Repo ghrepo.Interface
			// Number is the number argument value.
			Number int
		}
	}
	lockCreate        sync.RWMutex
	lockDelete        sync.RWMutex
	lockGet           sync.RWMutex
	lockIsPullRequest sync.RWMutex
	lockList          sync.RWMutex
	lockUploadTarget  sync.RWMutex
}

// Create calls CreateFunc.
func (mock *ArtifactClientMock) Create(repo ghrepo.Interface, issueNumber int, artifactType string, name string, body string) (*Artifact, error) {
	if mock.CreateFunc == nil {
		panic("ArtifactClientMock.CreateFunc: method is nil but ArtifactClient.Create was just called")
	}
	callInfo := struct {
		Repo         ghrepo.Interface
		IssueNumber  int
		ArtifactType string
		Name         string
		Body         string
	}{
		Repo:         repo,
		IssueNumber:  issueNumber,
		ArtifactType: artifactType,
		Name:         name,
		Body:         body,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(repo, issueNumber, artifactType, name, body)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedArtifactClient.CreateCalls())
func (mock *ArtifactClientMock) CreateCalls() []struct {
	Repo         ghrepo.Interface
	IssueNumber  int
	ArtifactType string
	Name         string
	Body         string
} {
	var calls []struct {
		Repo         ghrepo.Interface
		IssueNumber  int
		ArtifactType string
		Name         string
		Body         string
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *ArtifactClientMock) Delete(repo ghrepo.Interface, issueNumber int, number int) error {
	if mock.DeleteFunc == nil {
		panic("ArtifactClientMock.DeleteFunc: method is nil but ArtifactClient.Delete was just called")
	}
	callInfo := struct {
		Repo        ghrepo.Interface
		IssueNumber int
		Number      int
	}{
		Repo:        repo,
		IssueNumber: issueNumber,
		Number:      number,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(repo, issueNumber, number)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedArtifactClient.DeleteCalls())
func (mock *ArtifactClientMock) DeleteCalls() []struct {
	Repo        ghrepo.Interface
	IssueNumber int
	Number      int
} {
	var calls []struct {
		Repo        ghrepo.Interface
		IssueNumber int
		Number      int
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *ArtifactClientMock) Get(repo ghrepo.Interface, issueNumber int, number int) (*ArtifactWithVersions, error) {
	if mock.GetFunc == nil {
		panic("ArtifactClientMock.GetFunc: method is nil but ArtifactClient.Get was just called")
	}
	callInfo := struct {
		Repo        ghrepo.Interface
		IssueNumber int
		Number      int
	}{
		Repo:        repo,
		IssueNumber: issueNumber,
		Number:      number,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(repo, issueNumber, number)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedArtifactClient.GetCalls())
func (mock *ArtifactClientMock) GetCalls() []struct {
	Repo        ghrepo.Interface
	IssueNumber int
	Number      int
} {
	var calls []struct {
		Repo        ghrepo.Interface
		IssueNumber int
		Number      int
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// IsPullRequest calls IsPullRequestFunc.
func (mock *ArtifactClientMock) IsPullRequest(repo ghrepo.Interface, number int) (bool, error) {
	if mock.IsPullRequestFunc == nil {
		panic("ArtifactClientMock.IsPullRequestFunc: method is nil but ArtifactClient.IsPullRequest was just called")
	}
	callInfo := struct {
		Repo   ghrepo.Interface
		Number int
	}{
		Repo:   repo,
		Number: number,
	}
	mock.lockIsPullRequest.Lock()
	mock.calls.IsPullRequest = append(mock.calls.IsPullRequest, callInfo)
	mock.lockIsPullRequest.Unlock()
	return mock.IsPullRequestFunc(repo, number)
}

// IsPullRequestCalls gets all the calls that were made to IsPullRequest.
// Check the length with:
//
//	len(mockedArtifactClient.IsPullRequestCalls())
func (mock *ArtifactClientMock) IsPullRequestCalls() []struct {
	Repo   ghrepo.Interface
	Number int
} {
	var calls []struct {
		Repo   ghrepo.Interface
		Number int
	}
	mock.lockIsPullRequest.RLock()
	calls = mock.calls.IsPullRequest
	mock.lockIsPullRequest.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *ArtifactClientMock) List(repo ghrepo.Interface, issueNumber int, artifactType string, limit int) ([]Artifact, error) {
	if mock.ListFunc == nil {
		panic("ArtifactClientMock.ListFunc: method is nil but ArtifactClient.List was just called")
	}
	callInfo := struct {
		Repo         ghrepo.Interface
		IssueNumber  int
		ArtifactType string
		Limit        int
	}{
		Repo:         repo,
		IssueNumber:  issueNumber,
		ArtifactType: artifactType,
		Limit:        limit,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(repo, issueNumber, artifactType, limit)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedArtifactClient.ListCalls())
func (mock *ArtifactClientMock) ListCalls() []struct {
	Repo         ghrepo.Interface
	IssueNumber  int
	ArtifactType string
	Limit        int
} {
	var calls []struct {
		Repo         ghrepo.Interface
		IssueNumber  int
		ArtifactType string
		Limit        int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// UploadTarget calls UploadTargetFunc.
func (mock *ArtifactClientMock) UploadTarget(repo ghrepo.Interface, number int) (*UploadTarget, error) {
	if mock.UploadTargetFunc == nil {
		panic("ArtifactClientMock.UploadTargetFunc: method is nil but ArtifactClient.UploadTarget was just called")
	}
	callInfo := struct {
		Repo   ghrepo.Interface
		Number int
	}{
		Repo:   repo,
		Number: number,
	}
	mock.lockUploadTarget.Lock()
	mock.calls.UploadTarget = append(mock.calls.UploadTarget, callInfo)
	mock.lockUploadTarget.Unlock()
	return mock.UploadTargetFunc(repo, number)
}

// UploadTargetCalls gets all the calls that were made to UploadTarget.
// Check the length with:
//
//	len(mockedArtifactClient.UploadTargetCalls())
func (mock *ArtifactClientMock) UploadTargetCalls() []struct {
	Repo   ghrepo.Interface
	Number int
} {
	var calls []struct {
		Repo   ghrepo.Interface
		Number int
	}
	mock.lockUploadTarget.RLock()
	calls = mock.calls.UploadTarget
	mock.lockUploadTarget.RUnlock()
	return calls
}
