// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package client

import (
	"github.com/cli/cli/v2/internal/ghrepo"
	"sync"
)

// Ensure, that ArtifactClientMock does implement ArtifactClient.
// If this is not the case, regenerate this file with moq.
var _ ArtifactClient = &ArtifactClientMock{}

// ArtifactClientMock is a mock implementation of ArtifactClient.
//
//	func TestSomethingThatUsesArtifactClient(t *testing.T) {
//
//		// make and configure a mocked ArtifactClient
//		mockedArtifactClient := &ArtifactClientMock{
//			IsPullRequestFunc: func(repo ghrepo.Interface, number int) (bool, error) {
//				panic("mock out the IsPullRequest method")
//			},
//			ListFunc: func(repo ghrepo.Interface, issueNumber int, artifactType string, limit int) ([]Artifact, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedArtifactClient in code that requires ArtifactClient
//		// and then make assertions.
//
//	}
type ArtifactClientMock struct {
	// IsPullRequestFunc mocks the IsPullRequest method.
	IsPullRequestFunc func(repo ghrepo.Interface, number int) (bool, error)

	// ListFunc mocks the List method.
	ListFunc func(repo ghrepo.Interface, issueNumber int, artifactType string, limit int) ([]Artifact, error)

	// calls tracks calls to the methods.
	calls struct {
		// IsPullRequest holds details about calls to the IsPullRequest method.
		IsPullRequest []struct {
			// Repo is the repo argument value.
			Repo ghrepo.Interface
			// Number is the number argument value.
			Number int
		}
		// List holds details about calls to the List method.
		List []struct {
			// Repo is the repo argument value.
			Repo ghrepo.Interface
			// IssueNumber is the issueNumber argument value.
			IssueNumber int
			// ArtifactType is the artifactType argument value.
			ArtifactType string
			// Limit is the limit argument value.
			Limit int
		}
	}
	lockIsPullRequest sync.RWMutex
	lockList          sync.RWMutex
}

// IsPullRequest calls IsPullRequestFunc.
func (mock *ArtifactClientMock) IsPullRequest(repo ghrepo.Interface, number int) (bool, error) {
	if mock.IsPullRequestFunc == nil {
		panic("ArtifactClientMock.IsPullRequestFunc: method is nil but ArtifactClient.IsPullRequest was just called")
	}
	callInfo := struct {
		Repo   ghrepo.Interface
		Number int
	}{
		Repo:   repo,
		Number: number,
	}
	mock.lockIsPullRequest.Lock()
	mock.calls.IsPullRequest = append(mock.calls.IsPullRequest, callInfo)
	mock.lockIsPullRequest.Unlock()
	return mock.IsPullRequestFunc(repo, number)
}

// IsPullRequestCalls gets all the calls that were made to IsPullRequest.
// Check the length with:
//
//	len(mockedArtifactClient.IsPullRequestCalls())
func (mock *ArtifactClientMock) IsPullRequestCalls() []struct {
	Repo   ghrepo.Interface
	Number int
} {
	var calls []struct {
		Repo   ghrepo.Interface
		Number int
	}
	mock.lockIsPullRequest.RLock()
	calls = mock.calls.IsPullRequest
	mock.lockIsPullRequest.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *ArtifactClientMock) List(repo ghrepo.Interface, issueNumber int, artifactType string, limit int) ([]Artifact, error) {
	if mock.ListFunc == nil {
		panic("ArtifactClientMock.ListFunc: method is nil but ArtifactClient.List was just called")
	}
	callInfo := struct {
		Repo         ghrepo.Interface
		IssueNumber  int
		ArtifactType string
		Limit        int
	}{
		Repo:         repo,
		IssueNumber:  issueNumber,
		ArtifactType: artifactType,
		Limit:        limit,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(repo, issueNumber, artifactType, limit)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedArtifactClient.ListCalls())
func (mock *ArtifactClientMock) ListCalls() []struct {
	Repo         ghrepo.Interface
	IssueNumber  int
	ArtifactType string
	Limit        int
} {
	var calls []struct {
		Repo         ghrepo.Interface
		IssueNumber  int
		ArtifactType string
		Limit        int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
