// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ghcs

import (
	"context"
	"sync"

	"github.com/github/ghcs/internal/api"
)

// apiClientMock is a mock implementation of apiClient.
//
// 	func TestSomethingThatUsesapiClient(t *testing.T) {
//
// 		// make and configure a mocked apiClient
// 		mockedapiClient := &apiClientMock{
// 			DeleteCodespaceFunc: func(ctx context.Context, user string, name string) error {
// 				panic("mock out the DeleteCodespace method")
// 			},
// 			GetCodespaceFunc: func(ctx context.Context, token string, user string, name string) (*api.Codespace, error) {
// 				panic("mock out the GetCodespace method")
// 			},
// 			GetCodespaceTokenFunc: func(ctx context.Context, user string, name string) (string, error) {
// 				panic("mock out the GetCodespaceToken method")
// 			},
// 			GetUserFunc: func(ctx context.Context) (*api.User, error) {
// 				panic("mock out the GetUser method")
// 			},
// 			ListCodespacesFunc: func(ctx context.Context, user string) ([]*api.Codespace, error) {
// 				panic("mock out the ListCodespaces method")
// 			},
// 		}
//
// 		// use mockedapiClient in code that requires apiClient
// 		// and then make assertions.
//
// 	}
type apiClientMock struct {
	// DeleteCodespaceFunc mocks the DeleteCodespace method.
	DeleteCodespaceFunc func(ctx context.Context, user string, name string) error

	// GetCodespaceFunc mocks the GetCodespace method.
	GetCodespaceFunc func(ctx context.Context, token string, user string, name string) (*api.Codespace, error)

	// GetCodespaceTokenFunc mocks the GetCodespaceToken method.
	GetCodespaceTokenFunc func(ctx context.Context, user string, name string) (string, error)

	// GetUserFunc mocks the GetUser method.
	GetUserFunc func(ctx context.Context) (*api.User, error)

	// ListCodespacesFunc mocks the ListCodespaces method.
	ListCodespacesFunc func(ctx context.Context, user string) ([]*api.Codespace, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteCodespace holds details about calls to the DeleteCodespace method.
		DeleteCodespace []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User string
			// Name is the name argument value.
			Name string
		}
		// GetCodespace holds details about calls to the GetCodespace method.
		GetCodespace []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
			// User is the user argument value.
			User string
			// Name is the name argument value.
			Name string
		}
		// GetCodespaceToken holds details about calls to the GetCodespaceToken method.
		GetCodespaceToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User string
			// Name is the name argument value.
			Name string
		}
		// GetUser holds details about calls to the GetUser method.
		GetUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListCodespaces holds details about calls to the ListCodespaces method.
		ListCodespaces []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User string
		}
	}
	lockDeleteCodespace   sync.RWMutex
	lockGetCodespace      sync.RWMutex
	lockGetCodespaceToken sync.RWMutex
	lockGetUser           sync.RWMutex
	lockListCodespaces    sync.RWMutex
}

// DeleteCodespace calls DeleteCodespaceFunc.
func (mock *apiClientMock) DeleteCodespace(ctx context.Context, user string, name string) error {
	if mock.DeleteCodespaceFunc == nil {
		panic("apiClientMock.DeleteCodespaceFunc: method is nil but apiClient.DeleteCodespace was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User string
		Name string
	}{
		Ctx:  ctx,
		User: user,
		Name: name,
	}
	mock.lockDeleteCodespace.Lock()
	mock.calls.DeleteCodespace = append(mock.calls.DeleteCodespace, callInfo)
	mock.lockDeleteCodespace.Unlock()
	return mock.DeleteCodespaceFunc(ctx, user, name)
}

// DeleteCodespaceCalls gets all the calls that were made to DeleteCodespace.
// Check the length with:
//     len(mockedapiClient.DeleteCodespaceCalls())
func (mock *apiClientMock) DeleteCodespaceCalls() []struct {
	Ctx  context.Context
	User string
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		User string
		Name string
	}
	mock.lockDeleteCodespace.RLock()
	calls = mock.calls.DeleteCodespace
	mock.lockDeleteCodespace.RUnlock()
	return calls
}

// GetCodespace calls GetCodespaceFunc.
func (mock *apiClientMock) GetCodespace(ctx context.Context, token string, user string, name string) (*api.Codespace, error) {
	if mock.GetCodespaceFunc == nil {
		panic("apiClientMock.GetCodespaceFunc: method is nil but apiClient.GetCodespace was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
		User  string
		Name  string
	}{
		Ctx:   ctx,
		Token: token,
		User:  user,
		Name:  name,
	}
	mock.lockGetCodespace.Lock()
	mock.calls.GetCodespace = append(mock.calls.GetCodespace, callInfo)
	mock.lockGetCodespace.Unlock()
	return mock.GetCodespaceFunc(ctx, token, user, name)
}

// GetCodespaceCalls gets all the calls that were made to GetCodespace.
// Check the length with:
//     len(mockedapiClient.GetCodespaceCalls())
func (mock *apiClientMock) GetCodespaceCalls() []struct {
	Ctx   context.Context
	Token string
	User  string
	Name  string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
		User  string
		Name  string
	}
	mock.lockGetCodespace.RLock()
	calls = mock.calls.GetCodespace
	mock.lockGetCodespace.RUnlock()
	return calls
}

// GetCodespaceToken calls GetCodespaceTokenFunc.
func (mock *apiClientMock) GetCodespaceToken(ctx context.Context, user string, name string) (string, error) {
	if mock.GetCodespaceTokenFunc == nil {
		panic("apiClientMock.GetCodespaceTokenFunc: method is nil but apiClient.GetCodespaceToken was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User string
		Name string
	}{
		Ctx:  ctx,
		User: user,
		Name: name,
	}
	mock.lockGetCodespaceToken.Lock()
	mock.calls.GetCodespaceToken = append(mock.calls.GetCodespaceToken, callInfo)
	mock.lockGetCodespaceToken.Unlock()
	return mock.GetCodespaceTokenFunc(ctx, user, name)
}

// GetCodespaceTokenCalls gets all the calls that were made to GetCodespaceToken.
// Check the length with:
//     len(mockedapiClient.GetCodespaceTokenCalls())
func (mock *apiClientMock) GetCodespaceTokenCalls() []struct {
	Ctx  context.Context
	User string
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		User string
		Name string
	}
	mock.lockGetCodespaceToken.RLock()
	calls = mock.calls.GetCodespaceToken
	mock.lockGetCodespaceToken.RUnlock()
	return calls
}

// GetUser calls GetUserFunc.
func (mock *apiClientMock) GetUser(ctx context.Context) (*api.User, error) {
	if mock.GetUserFunc == nil {
		panic("apiClientMock.GetUserFunc: method is nil but apiClient.GetUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetUser.Lock()
	mock.calls.GetUser = append(mock.calls.GetUser, callInfo)
	mock.lockGetUser.Unlock()
	return mock.GetUserFunc(ctx)
}

// GetUserCalls gets all the calls that were made to GetUser.
// Check the length with:
//     len(mockedapiClient.GetUserCalls())
func (mock *apiClientMock) GetUserCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetUser.RLock()
	calls = mock.calls.GetUser
	mock.lockGetUser.RUnlock()
	return calls
}

// ListCodespaces calls ListCodespacesFunc.
func (mock *apiClientMock) ListCodespaces(ctx context.Context, user string) ([]*api.Codespace, error) {
	if mock.ListCodespacesFunc == nil {
		panic("apiClientMock.ListCodespacesFunc: method is nil but apiClient.ListCodespaces was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User string
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockListCodespaces.Lock()
	mock.calls.ListCodespaces = append(mock.calls.ListCodespaces, callInfo)
	mock.lockListCodespaces.Unlock()
	return mock.ListCodespacesFunc(ctx, user)
}

// ListCodespacesCalls gets all the calls that were made to ListCodespaces.
// Check the length with:
//     len(mockedapiClient.ListCodespacesCalls())
func (mock *apiClientMock) ListCodespacesCalls() []struct {
	Ctx  context.Context
	User string
} {
	var calls []struct {
		Ctx  context.Context
		User string
	}
	mock.lockListCodespaces.RLock()
	calls = mock.calls.ListCodespaces
	mock.lockListCodespaces.RUnlock()
	return calls
}
