// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: ssh/ssh_server_host_service.v1.proto

package ssh

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRemoteServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserPublicKey string `protobuf:"bytes,1,opt,name=UserPublicKey,proto3" json:"UserPublicKey,omitempty"`
}

func (x *StartRemoteServerRequest) Reset() {
	*x = StartRemoteServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssh_ssh_server_host_service_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRemoteServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRemoteServerRequest) ProtoMessage() {}

func (x *StartRemoteServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ssh_ssh_server_host_service_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRemoteServerRequest.ProtoReflect.Descriptor instead.
func (*StartRemoteServerRequest) Descriptor() ([]byte, []int) {
	return file_ssh_ssh_server_host_service_v1_proto_rawDescGZIP(), []int{0}
}

func (x *StartRemoteServerRequest) GetUserPublicKey() string {
	if x != nil {
		return x.UserPublicKey
	}
	return ""
}

type StartRemoteServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result     bool   `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	ServerPort string `protobuf:"bytes,2,opt,name=ServerPort,proto3" json:"ServerPort,omitempty"`
	User       string `protobuf:"bytes,3,opt,name=User,proto3" json:"User,omitempty"`
	Message    string `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *StartRemoteServerResponse) Reset() {
	*x = StartRemoteServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssh_ssh_server_host_service_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRemoteServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRemoteServerResponse) ProtoMessage() {}

func (x *StartRemoteServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ssh_ssh_server_host_service_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRemoteServerResponse.ProtoReflect.Descriptor instead.
func (*StartRemoteServerResponse) Descriptor() ([]byte, []int) {
	return file_ssh_ssh_server_host_service_v1_proto_rawDescGZIP(), []int{1}
}

func (x *StartRemoteServerResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *StartRemoteServerResponse) GetServerPort() string {
	if x != nil {
		return x.ServerPort
	}
	return ""
}

func (x *StartRemoteServerResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *StartRemoteServerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ssh_ssh_server_host_service_v1_proto protoreflect.FileDescriptor

var file_ssh_ssh_server_host_service_v1_proto_rawDesc = []byte{
	0x0a, 0x24, 0x73, 0x73, 0x68, 0x2f, 0x73, 0x73, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x27, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22,
	0x40, 0x0a, 0x18, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x22, 0x81, 0x01, 0x0a, 0x19, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xb1, 0x01, 0x0a, 0x0d, 0x53, 0x73, 0x68, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x9f, 0x01, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x73, 0x79,
	0x6e, 0x63, 0x12, 0x41, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x2e,
	0x47, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48, 0x6f,
	0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x42, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x73,
	0x73, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ssh_ssh_server_host_service_v1_proto_rawDescOnce sync.Once
	file_ssh_ssh_server_host_service_v1_proto_rawDescData = file_ssh_ssh_server_host_service_v1_proto_rawDesc
)

func file_ssh_ssh_server_host_service_v1_proto_rawDescGZIP() []byte {
	file_ssh_ssh_server_host_service_v1_proto_rawDescOnce.Do(func() {
		file_ssh_ssh_server_host_service_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_ssh_ssh_server_host_service_v1_proto_rawDescData)
	})
	return file_ssh_ssh_server_host_service_v1_proto_rawDescData
}

var file_ssh_ssh_server_host_service_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ssh_ssh_server_host_service_v1_proto_goTypes = []interface{}{
	(*StartRemoteServerRequest)(nil),  // 0: Codespaces.Grpc.SshServerHostService.v1.StartRemoteServerRequest
	(*StartRemoteServerResponse)(nil), // 1: Codespaces.Grpc.SshServerHostService.v1.StartRemoteServerResponse
}
var file_ssh_ssh_server_host_service_v1_proto_depIdxs = []int32{
	0, // 0: Codespaces.Grpc.SshServerHostService.v1.SshServerHost.StartRemoteServerAsync:input_type -> Codespaces.Grpc.SshServerHostService.v1.StartRemoteServerRequest
	1, // 1: Codespaces.Grpc.SshServerHostService.v1.SshServerHost.StartRemoteServerAsync:output_type -> Codespaces.Grpc.SshServerHostService.v1.StartRemoteServerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ssh_ssh_server_host_service_v1_proto_init() }
func file_ssh_ssh_server_host_service_v1_proto_init() {
	if File_ssh_ssh_server_host_service_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ssh_ssh_server_host_service_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRemoteServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssh_ssh_server_host_service_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRemoteServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ssh_ssh_server_host_service_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ssh_ssh_server_host_service_v1_proto_goTypes,
		DependencyIndexes: file_ssh_ssh_server_host_service_v1_proto_depIdxs,
		MessageInfos:      file_ssh_ssh_server_host_service_v1_proto_msgTypes,
	}.Build()
	File_ssh_ssh_server_host_service_v1_proto = out.File
	file_ssh_ssh_server_host_service_v1_proto_rawDesc = nil
	file_ssh_ssh_server_host_service_v1_proto_goTypes = nil
	file_ssh_ssh_server_host_service_v1_proto_depIdxs = nil
}
