// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.3
// source: CodespaceHostService.v1.proto

package codespace

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CodespaceHostClient is the client API for CodespaceHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CodespaceHostClient interface {
	NotifyCodespaceOfClientActivity(ctx context.Context, in *NotifyCodespaceOfClientActivityRequest, opts ...grpc.CallOption) (*NotifyCodespaceOfClientActivityResponse, error)
}

type codespaceHostClient struct {
	cc grpc.ClientConnInterface
}

func NewCodespaceHostClient(cc grpc.ClientConnInterface) CodespaceHostClient {
	return &codespaceHostClient{cc}
}

func (c *codespaceHostClient) NotifyCodespaceOfClientActivity(ctx context.Context, in *NotifyCodespaceOfClientActivityRequest, opts ...grpc.CallOption) (*NotifyCodespaceOfClientActivityResponse, error) {
	out := new(NotifyCodespaceOfClientActivityResponse)
	err := c.cc.Invoke(ctx, "/Codespaces.Grpc.CodespaceHostService.v1.CodespaceHost/NotifyCodespaceOfClientActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodespaceHostServer is the server API for CodespaceHost service.
// All implementations must embed UnimplementedCodespaceHostServer
// for forward compatibility
type CodespaceHostServer interface {
	NotifyCodespaceOfClientActivity(context.Context, *NotifyCodespaceOfClientActivityRequest) (*NotifyCodespaceOfClientActivityResponse, error)
	mustEmbedUnimplementedCodespaceHostServer()
}

// UnimplementedCodespaceHostServer must be embedded to have forward compatible implementations.
type UnimplementedCodespaceHostServer struct {
}

func (UnimplementedCodespaceHostServer) NotifyCodespaceOfClientActivity(context.Context, *NotifyCodespaceOfClientActivityRequest) (*NotifyCodespaceOfClientActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyCodespaceOfClientActivity not implemented")
}
func (UnimplementedCodespaceHostServer) mustEmbedUnimplementedCodespaceHostServer() {}

// UnsafeCodespaceHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodespaceHostServer will
// result in compilation errors.
type UnsafeCodespaceHostServer interface {
	mustEmbedUnimplementedCodespaceHostServer()
}

func RegisterCodespaceHostServer(s grpc.ServiceRegistrar, srv CodespaceHostServer) {
	s.RegisterService(&CodespaceHost_ServiceDesc, srv)
}

func _CodespaceHost_NotifyCodespaceOfClientActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyCodespaceOfClientActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodespaceHostServer).NotifyCodespaceOfClientActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Codespaces.Grpc.CodespaceHostService.v1.CodespaceHost/NotifyCodespaceOfClientActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodespaceHostServer).NotifyCodespaceOfClientActivity(ctx, req.(*NotifyCodespaceOfClientActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CodespaceHost_ServiceDesc is the grpc.ServiceDesc for CodespaceHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodespaceHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Codespaces.Grpc.CodespaceHostService.v1.CodespaceHost",
	HandlerType: (*CodespaceHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyCodespaceOfClientActivity",
			Handler:    _CodespaceHost_NotifyCodespaceOfClientActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "CodespaceHostService.v1.proto",
}
