// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package grpctunnel

import (
	"sync"
)

// Ensure, that withProgresssMock does implement withProgresss.
// If this is not the case, regenerate this file with moq.
var _ withProgresss = &withProgresssMock{}

// withProgresssMock is a mock implementation of withProgresss.
//
//	func TestSomethingThatUseswithProgresss(t *testing.T) {
//
//		// make and configure a mocked withProgresss
//		mockedwithProgresss := &withProgresssMock{
//			StartProgressIndicatorWithLabelFunc: func(s string)  {
//				panic("mock out the StartProgressIndicatorWithLabel method")
//			},
//			StopProgressIndicatorFunc: func()  {
//				panic("mock out the StopProgressIndicator method")
//			},
//		}
//
//		// use mockedwithProgresss in code that requires withProgresss
//		// and then make assertions.
//
//	}
type withProgresssMock struct {
	// StartProgressIndicatorWithLabelFunc mocks the StartProgressIndicatorWithLabel method.
	StartProgressIndicatorWithLabelFunc func(s string)

	// StopProgressIndicatorFunc mocks the StopProgressIndicator method.
	StopProgressIndicatorFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// StartProgressIndicatorWithLabel holds details about calls to the StartProgressIndicatorWithLabel method.
		StartProgressIndicatorWithLabel []struct {
			// S is the s argument value.
			S string
		}
		// StopProgressIndicator holds details about calls to the StopProgressIndicator method.
		StopProgressIndicator []struct {
		}
	}
	lockStartProgressIndicatorWithLabel sync.RWMutex
	lockStopProgressIndicator           sync.RWMutex
}

// StartProgressIndicatorWithLabel calls StartProgressIndicatorWithLabelFunc.
func (mock *withProgresssMock) StartProgressIndicatorWithLabel(s string) {
	if mock.StartProgressIndicatorWithLabelFunc == nil {
		panic("withProgresssMock.StartProgressIndicatorWithLabelFunc: method is nil but withProgresss.StartProgressIndicatorWithLabel was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockStartProgressIndicatorWithLabel.Lock()
	mock.calls.StartProgressIndicatorWithLabel = append(mock.calls.StartProgressIndicatorWithLabel, callInfo)
	mock.lockStartProgressIndicatorWithLabel.Unlock()
	mock.StartProgressIndicatorWithLabelFunc(s)
}

// StartProgressIndicatorWithLabelCalls gets all the calls that were made to StartProgressIndicatorWithLabel.
// Check the length with:
//
//	len(mockedwithProgresss.StartProgressIndicatorWithLabelCalls())
func (mock *withProgresssMock) StartProgressIndicatorWithLabelCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockStartProgressIndicatorWithLabel.RLock()
	calls = mock.calls.StartProgressIndicatorWithLabel
	mock.lockStartProgressIndicatorWithLabel.RUnlock()
	return calls
}

// StopProgressIndicator calls StopProgressIndicatorFunc.
func (mock *withProgresssMock) StopProgressIndicator() {
	if mock.StopProgressIndicatorFunc == nil {
		panic("withProgresssMock.StopProgressIndicatorFunc: method is nil but withProgresss.StopProgressIndicator was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStopProgressIndicator.Lock()
	mock.calls.StopProgressIndicator = append(mock.calls.StopProgressIndicator, callInfo)
	mock.lockStopProgressIndicator.Unlock()
	mock.StopProgressIndicatorFunc()
}

// StopProgressIndicatorCalls gets all the calls that were made to StopProgressIndicator.
// Check the length with:
//
//	len(mockedwithProgresss.StopProgressIndicatorCalls())
func (mock *withProgresssMock) StopProgressIndicatorCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStopProgressIndicator.RLock()
	calls = mock.calls.StopProgressIndicator
	mock.lockStopProgressIndicator.RUnlock()
	return calls
}
