// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package grpctunnel

import (
	"context"
	"github.com/cli/cli/v2/internal/codespaces/portforwarder"
	"github.com/microsoft/dev-tunnels/go/tunnels"
	"io"
	"net"
	"sync"
)

// Ensure, that PortForwarderMock does implement portforwarder.PortForwarder.
// If this is not the case, regenerate this file with moq.
var _ portforwarder.PortForwarder = &PortForwarderMock{}

// PortForwarderMock is a mock implementation of portforwarder.PortForwarder.
//
//	func TestSomethingThatUsesPortForwarder(t *testing.T) {
//
//		// make and configure a mocked portforwarder.PortForwarder
//		mockedPortForwarder := &PortForwarderMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			ConnectToForwardedPortFunc: func(ctx context.Context, conn io.ReadWriteCloser, opts portforwarder.ForwardPortOpts) error {
//				panic("mock out the ConnectToForwardedPort method")
//			},
//			ForwardPortFunc: func(ctx context.Context, opts portforwarder.ForwardPortOpts) error {
//				panic("mock out the ForwardPort method")
//			},
//			ForwardPortToListenerFunc: func(ctx context.Context, opts portforwarder.ForwardPortOpts, listener *net.TCPListener) error {
//				panic("mock out the ForwardPortToListener method")
//			},
//			GetKeepAliveReasonFunc: func() string {
//				panic("mock out the GetKeepAliveReason method")
//			},
//			KeepAliveFunc: func(reason string)  {
//				panic("mock out the KeepAlive method")
//			},
//			ListPortsFunc: func(ctx context.Context) ([]*tunnels.TunnelPort, error) {
//				panic("mock out the ListPorts method")
//			},
//			UpdatePortVisibilityFunc: func(ctx context.Context, remotePort int, visibility string) error {
//				panic("mock out the UpdatePortVisibility method")
//			},
//		}
//
//		// use mockedPortForwarder in code that requires portforwarder.PortForwarder
//		// and then make assertions.
//
//	}
type PortForwarderMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// ConnectToForwardedPortFunc mocks the ConnectToForwardedPort method.
	ConnectToForwardedPortFunc func(ctx context.Context, conn io.ReadWriteCloser, opts portforwarder.ForwardPortOpts) error

	// ForwardPortFunc mocks the ForwardPort method.
	ForwardPortFunc func(ctx context.Context, opts portforwarder.ForwardPortOpts) error

	// ForwardPortToListenerFunc mocks the ForwardPortToListener method.
	ForwardPortToListenerFunc func(ctx context.Context, opts portforwarder.ForwardPortOpts, listener *net.TCPListener) error

	// GetKeepAliveReasonFunc mocks the GetKeepAliveReason method.
	GetKeepAliveReasonFunc func() string

	// KeepAliveFunc mocks the KeepAlive method.
	KeepAliveFunc func(reason string)

	// ListPortsFunc mocks the ListPorts method.
	ListPortsFunc func(ctx context.Context) ([]*tunnels.TunnelPort, error)

	// UpdatePortVisibilityFunc mocks the UpdatePortVisibility method.
	UpdatePortVisibilityFunc func(ctx context.Context, remotePort int, visibility string) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// ConnectToForwardedPort holds details about calls to the ConnectToForwardedPort method.
		ConnectToForwardedPort []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Conn is the conn argument value.
			Conn io.ReadWriteCloser
			// Opts is the opts argument value.
			Opts portforwarder.ForwardPortOpts
		}
		// ForwardPort holds details about calls to the ForwardPort method.
		ForwardPort []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts portforwarder.ForwardPortOpts
		}
		// ForwardPortToListener holds details about calls to the ForwardPortToListener method.
		ForwardPortToListener []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts portforwarder.ForwardPortOpts
			// Listener is the listener argument value.
			Listener *net.TCPListener
		}
		// GetKeepAliveReason holds details about calls to the GetKeepAliveReason method.
		GetKeepAliveReason []struct {
		}
		// KeepAlive holds details about calls to the KeepAlive method.
		KeepAlive []struct {
			// Reason is the reason argument value.
			Reason string
		}
		// ListPorts holds details about calls to the ListPorts method.
		ListPorts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UpdatePortVisibility holds details about calls to the UpdatePortVisibility method.
		UpdatePortVisibility []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RemotePort is the remotePort argument value.
			RemotePort int
			// Visibility is the visibility argument value.
			Visibility string
		}
	}
	lockClose                  sync.RWMutex
	lockConnectToForwardedPort sync.RWMutex
	lockForwardPort            sync.RWMutex
	lockForwardPortToListener  sync.RWMutex
	lockGetKeepAliveReason     sync.RWMutex
	lockKeepAlive              sync.RWMutex
	lockListPorts              sync.RWMutex
	lockUpdatePortVisibility   sync.RWMutex
}

// Close calls CloseFunc.
func (mock *PortForwarderMock) Close() error {
	if mock.CloseFunc == nil {
		panic("PortForwarderMock.CloseFunc: method is nil but PortForwarder.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedPortForwarder.CloseCalls())
func (mock *PortForwarderMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// ConnectToForwardedPort calls ConnectToForwardedPortFunc.
func (mock *PortForwarderMock) ConnectToForwardedPort(ctx context.Context, conn io.ReadWriteCloser, opts portforwarder.ForwardPortOpts) error {
	if mock.ConnectToForwardedPortFunc == nil {
		panic("PortForwarderMock.ConnectToForwardedPortFunc: method is nil but PortForwarder.ConnectToForwardedPort was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Conn io.ReadWriteCloser
		Opts portforwarder.ForwardPortOpts
	}{
		Ctx:  ctx,
		Conn: conn,
		Opts: opts,
	}
	mock.lockConnectToForwardedPort.Lock()
	mock.calls.ConnectToForwardedPort = append(mock.calls.ConnectToForwardedPort, callInfo)
	mock.lockConnectToForwardedPort.Unlock()
	return mock.ConnectToForwardedPortFunc(ctx, conn, opts)
}

// ConnectToForwardedPortCalls gets all the calls that were made to ConnectToForwardedPort.
// Check the length with:
//
//	len(mockedPortForwarder.ConnectToForwardedPortCalls())
func (mock *PortForwarderMock) ConnectToForwardedPortCalls() []struct {
	Ctx  context.Context
	Conn io.ReadWriteCloser
	Opts portforwarder.ForwardPortOpts
} {
	var calls []struct {
		Ctx  context.Context
		Conn io.ReadWriteCloser
		Opts portforwarder.ForwardPortOpts
	}
	mock.lockConnectToForwardedPort.RLock()
	calls = mock.calls.ConnectToForwardedPort
	mock.lockConnectToForwardedPort.RUnlock()
	return calls
}

// ForwardPort calls ForwardPortFunc.
func (mock *PortForwarderMock) ForwardPort(ctx context.Context, opts portforwarder.ForwardPortOpts) error {
	if mock.ForwardPortFunc == nil {
		panic("PortForwarderMock.ForwardPortFunc: method is nil but PortForwarder.ForwardPort was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts portforwarder.ForwardPortOpts
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockForwardPort.Lock()
	mock.calls.ForwardPort = append(mock.calls.ForwardPort, callInfo)
	mock.lockForwardPort.Unlock()
	return mock.ForwardPortFunc(ctx, opts)
}

// ForwardPortCalls gets all the calls that were made to ForwardPort.
// Check the length with:
//
//	len(mockedPortForwarder.ForwardPortCalls())
func (mock *PortForwarderMock) ForwardPortCalls() []struct {
	Ctx  context.Context
	Opts portforwarder.ForwardPortOpts
} {
	var calls []struct {
		Ctx  context.Context
		Opts portforwarder.ForwardPortOpts
	}
	mock.lockForwardPort.RLock()
	calls = mock.calls.ForwardPort
	mock.lockForwardPort.RUnlock()
	return calls
}

// ForwardPortToListener calls ForwardPortToListenerFunc.
func (mock *PortForwarderMock) ForwardPortToListener(ctx context.Context, opts portforwarder.ForwardPortOpts, listener *net.TCPListener) error {
	if mock.ForwardPortToListenerFunc == nil {
		panic("PortForwarderMock.ForwardPortToListenerFunc: method is nil but PortForwarder.ForwardPortToListener was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Opts     portforwarder.ForwardPortOpts
		Listener *net.TCPListener
	}{
		Ctx:      ctx,
		Opts:     opts,
		Listener: listener,
	}
	mock.lockForwardPortToListener.Lock()
	mock.calls.ForwardPortToListener = append(mock.calls.ForwardPortToListener, callInfo)
	mock.lockForwardPortToListener.Unlock()
	return mock.ForwardPortToListenerFunc(ctx, opts, listener)
}

// ForwardPortToListenerCalls gets all the calls that were made to ForwardPortToListener.
// Check the length with:
//
//	len(mockedPortForwarder.ForwardPortToListenerCalls())
func (mock *PortForwarderMock) ForwardPortToListenerCalls() []struct {
	Ctx      context.Context
	Opts     portforwarder.ForwardPortOpts
	Listener *net.TCPListener
} {
	var calls []struct {
		Ctx      context.Context
		Opts     portforwarder.ForwardPortOpts
		Listener *net.TCPListener
	}
	mock.lockForwardPortToListener.RLock()
	calls = mock.calls.ForwardPortToListener
	mock.lockForwardPortToListener.RUnlock()
	return calls
}

// GetKeepAliveReason calls GetKeepAliveReasonFunc.
func (mock *PortForwarderMock) GetKeepAliveReason() string {
	if mock.GetKeepAliveReasonFunc == nil {
		panic("PortForwarderMock.GetKeepAliveReasonFunc: method is nil but PortForwarder.GetKeepAliveReason was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetKeepAliveReason.Lock()
	mock.calls.GetKeepAliveReason = append(mock.calls.GetKeepAliveReason, callInfo)
	mock.lockGetKeepAliveReason.Unlock()
	return mock.GetKeepAliveReasonFunc()
}

// GetKeepAliveReasonCalls gets all the calls that were made to GetKeepAliveReason.
// Check the length with:
//
//	len(mockedPortForwarder.GetKeepAliveReasonCalls())
func (mock *PortForwarderMock) GetKeepAliveReasonCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetKeepAliveReason.RLock()
	calls = mock.calls.GetKeepAliveReason
	mock.lockGetKeepAliveReason.RUnlock()
	return calls
}

// KeepAlive calls KeepAliveFunc.
func (mock *PortForwarderMock) KeepAlive(reason string) {
	if mock.KeepAliveFunc == nil {
		panic("PortForwarderMock.KeepAliveFunc: method is nil but PortForwarder.KeepAlive was just called")
	}
	callInfo := struct {
		Reason string
	}{
		Reason: reason,
	}
	mock.lockKeepAlive.Lock()
	mock.calls.KeepAlive = append(mock.calls.KeepAlive, callInfo)
	mock.lockKeepAlive.Unlock()
	mock.KeepAliveFunc(reason)
}

// KeepAliveCalls gets all the calls that were made to KeepAlive.
// Check the length with:
//
//	len(mockedPortForwarder.KeepAliveCalls())
func (mock *PortForwarderMock) KeepAliveCalls() []struct {
	Reason string
} {
	var calls []struct {
		Reason string
	}
	mock.lockKeepAlive.RLock()
	calls = mock.calls.KeepAlive
	mock.lockKeepAlive.RUnlock()
	return calls
}

// ListPorts calls ListPortsFunc.
func (mock *PortForwarderMock) ListPorts(ctx context.Context) ([]*tunnels.TunnelPort, error) {
	if mock.ListPortsFunc == nil {
		panic("PortForwarderMock.ListPortsFunc: method is nil but PortForwarder.ListPorts was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListPorts.Lock()
	mock.calls.ListPorts = append(mock.calls.ListPorts, callInfo)
	mock.lockListPorts.Unlock()
	return mock.ListPortsFunc(ctx)
}

// ListPortsCalls gets all the calls that were made to ListPorts.
// Check the length with:
//
//	len(mockedPortForwarder.ListPortsCalls())
func (mock *PortForwarderMock) ListPortsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListPorts.RLock()
	calls = mock.calls.ListPorts
	mock.lockListPorts.RUnlock()
	return calls
}

// UpdatePortVisibility calls UpdatePortVisibilityFunc.
func (mock *PortForwarderMock) UpdatePortVisibility(ctx context.Context, remotePort int, visibility string) error {
	if mock.UpdatePortVisibilityFunc == nil {
		panic("PortForwarderMock.UpdatePortVisibilityFunc: method is nil but PortForwarder.UpdatePortVisibility was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		RemotePort int
		Visibility string
	}{
		Ctx:        ctx,
		RemotePort: remotePort,
		Visibility: visibility,
	}
	mock.lockUpdatePortVisibility.Lock()
	mock.calls.UpdatePortVisibility = append(mock.calls.UpdatePortVisibility, callInfo)
	mock.lockUpdatePortVisibility.Unlock()
	return mock.UpdatePortVisibilityFunc(ctx, remotePort, visibility)
}

// UpdatePortVisibilityCalls gets all the calls that were made to UpdatePortVisibility.
// Check the length with:
//
//	len(mockedPortForwarder.UpdatePortVisibilityCalls())
func (mock *PortForwarderMock) UpdatePortVisibilityCalls() []struct {
	Ctx        context.Context
	RemotePort int
	Visibility string
} {
	var calls []struct {
		Ctx        context.Context
		RemotePort int
		Visibility string
	}
	mock.lockUpdatePortVisibility.RLock()
	calls = mock.calls.UpdatePortVisibility
	mock.lockUpdatePortVisibility.RUnlock()
	return calls
}
