// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package grpctunnel

import (
	"context"
	"github.com/cli/cli/v2/internal/codespaces/rpc"
	"sync"
)

// Ensure, that InvokerMock does implement rpc.Invoker.
// If this is not the case, regenerate this file with moq.
var _ rpc.Invoker = &InvokerMock{}

// InvokerMock is a mock implementation of rpc.Invoker.
//
//	func TestSomethingThatUsesInvoker(t *testing.T) {
//
//		// make and configure a mocked rpc.Invoker
//		mockedInvoker := &InvokerMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			KeepAliveFunc: func()  {
//				panic("mock out the KeepAlive method")
//			},
//			RebuildContainerFunc: func(ctx context.Context, full bool) error {
//				panic("mock out the RebuildContainer method")
//			},
//			StartJupyterServerFunc: func(ctx context.Context) (int, string, error) {
//				panic("mock out the StartJupyterServer method")
//			},
//			StartSSHServerFunc: func(ctx context.Context) (int, string, error) {
//				panic("mock out the StartSSHServer method")
//			},
//			StartSSHServerWithOptionsFunc: func(ctx context.Context, options rpc.StartSSHServerOptions) (int, string, error) {
//				panic("mock out the StartSSHServerWithOptions method")
//			},
//		}
//
//		// use mockedInvoker in code that requires rpc.Invoker
//		// and then make assertions.
//
//	}
type InvokerMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// KeepAliveFunc mocks the KeepAlive method.
	KeepAliveFunc func()

	// RebuildContainerFunc mocks the RebuildContainer method.
	RebuildContainerFunc func(ctx context.Context, full bool) error

	// StartJupyterServerFunc mocks the StartJupyterServer method.
	StartJupyterServerFunc func(ctx context.Context) (int, string, error)

	// StartSSHServerFunc mocks the StartSSHServer method.
	StartSSHServerFunc func(ctx context.Context) (int, string, error)

	// StartSSHServerWithOptionsFunc mocks the StartSSHServerWithOptions method.
	StartSSHServerWithOptionsFunc func(ctx context.Context, options rpc.StartSSHServerOptions) (int, string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// KeepAlive holds details about calls to the KeepAlive method.
		KeepAlive []struct {
		}
		// RebuildContainer holds details about calls to the RebuildContainer method.
		RebuildContainer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Full is the full argument value.
			Full bool
		}
		// StartJupyterServer holds details about calls to the StartJupyterServer method.
		StartJupyterServer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// StartSSHServer holds details about calls to the StartSSHServer method.
		StartSSHServer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// StartSSHServerWithOptions holds details about calls to the StartSSHServerWithOptions method.
		StartSSHServerWithOptions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Options is the options argument value.
			Options rpc.StartSSHServerOptions
		}
	}
	lockClose                     sync.RWMutex
	lockKeepAlive                 sync.RWMutex
	lockRebuildContainer          sync.RWMutex
	lockStartJupyterServer        sync.RWMutex
	lockStartSSHServer            sync.RWMutex
	lockStartSSHServerWithOptions sync.RWMutex
}

// Close calls CloseFunc.
func (mock *InvokerMock) Close() error {
	if mock.CloseFunc == nil {
		panic("InvokerMock.CloseFunc: method is nil but Invoker.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedInvoker.CloseCalls())
func (mock *InvokerMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// KeepAlive calls KeepAliveFunc.
func (mock *InvokerMock) KeepAlive() {
	if mock.KeepAliveFunc == nil {
		panic("InvokerMock.KeepAliveFunc: method is nil but Invoker.KeepAlive was just called")
	}
	callInfo := struct {
	}{}
	mock.lockKeepAlive.Lock()
	mock.calls.KeepAlive = append(mock.calls.KeepAlive, callInfo)
	mock.lockKeepAlive.Unlock()
	mock.KeepAliveFunc()
}

// KeepAliveCalls gets all the calls that were made to KeepAlive.
// Check the length with:
//
//	len(mockedInvoker.KeepAliveCalls())
func (mock *InvokerMock) KeepAliveCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockKeepAlive.RLock()
	calls = mock.calls.KeepAlive
	mock.lockKeepAlive.RUnlock()
	return calls
}

// RebuildContainer calls RebuildContainerFunc.
func (mock *InvokerMock) RebuildContainer(ctx context.Context, full bool) error {
	if mock.RebuildContainerFunc == nil {
		panic("InvokerMock.RebuildContainerFunc: method is nil but Invoker.RebuildContainer was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Full bool
	}{
		Ctx:  ctx,
		Full: full,
	}
	mock.lockRebuildContainer.Lock()
	mock.calls.RebuildContainer = append(mock.calls.RebuildContainer, callInfo)
	mock.lockRebuildContainer.Unlock()
	return mock.RebuildContainerFunc(ctx, full)
}

// RebuildContainerCalls gets all the calls that were made to RebuildContainer.
// Check the length with:
//
//	len(mockedInvoker.RebuildContainerCalls())
func (mock *InvokerMock) RebuildContainerCalls() []struct {
	Ctx  context.Context
	Full bool
} {
	var calls []struct {
		Ctx  context.Context
		Full bool
	}
	mock.lockRebuildContainer.RLock()
	calls = mock.calls.RebuildContainer
	mock.lockRebuildContainer.RUnlock()
	return calls
}

// StartJupyterServer calls StartJupyterServerFunc.
func (mock *InvokerMock) StartJupyterServer(ctx context.Context) (int, string, error) {
	if mock.StartJupyterServerFunc == nil {
		panic("InvokerMock.StartJupyterServerFunc: method is nil but Invoker.StartJupyterServer was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStartJupyterServer.Lock()
	mock.calls.StartJupyterServer = append(mock.calls.StartJupyterServer, callInfo)
	mock.lockStartJupyterServer.Unlock()
	return mock.StartJupyterServerFunc(ctx)
}

// StartJupyterServerCalls gets all the calls that were made to StartJupyterServer.
// Check the length with:
//
//	len(mockedInvoker.StartJupyterServerCalls())
func (mock *InvokerMock) StartJupyterServerCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStartJupyterServer.RLock()
	calls = mock.calls.StartJupyterServer
	mock.lockStartJupyterServer.RUnlock()
	return calls
}

// StartSSHServer calls StartSSHServerFunc.
func (mock *InvokerMock) StartSSHServer(ctx context.Context) (int, string, error) {
	if mock.StartSSHServerFunc == nil {
		panic("InvokerMock.StartSSHServerFunc: method is nil but Invoker.StartSSHServer was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStartSSHServer.Lock()
	mock.calls.StartSSHServer = append(mock.calls.StartSSHServer, callInfo)
	mock.lockStartSSHServer.Unlock()
	return mock.StartSSHServerFunc(ctx)
}

// StartSSHServerCalls gets all the calls that were made to StartSSHServer.
// Check the length with:
//
//	len(mockedInvoker.StartSSHServerCalls())
func (mock *InvokerMock) StartSSHServerCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStartSSHServer.RLock()
	calls = mock.calls.StartSSHServer
	mock.lockStartSSHServer.RUnlock()
	return calls
}

// StartSSHServerWithOptions calls StartSSHServerWithOptionsFunc.
func (mock *InvokerMock) StartSSHServerWithOptions(ctx context.Context, options rpc.StartSSHServerOptions) (int, string, error) {
	if mock.StartSSHServerWithOptionsFunc == nil {
		panic("InvokerMock.StartSSHServerWithOptionsFunc: method is nil but Invoker.StartSSHServerWithOptions was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Options rpc.StartSSHServerOptions
	}{
		Ctx:     ctx,
		Options: options,
	}
	mock.lockStartSSHServerWithOptions.Lock()
	mock.calls.StartSSHServerWithOptions = append(mock.calls.StartSSHServerWithOptions, callInfo)
	mock.lockStartSSHServerWithOptions.Unlock()
	return mock.StartSSHServerWithOptionsFunc(ctx, options)
}

// StartSSHServerWithOptionsCalls gets all the calls that were made to StartSSHServerWithOptions.
// Check the length with:
//
//	len(mockedInvoker.StartSSHServerWithOptionsCalls())
func (mock *InvokerMock) StartSSHServerWithOptionsCalls() []struct {
	Ctx     context.Context
	Options rpc.StartSSHServerOptions
} {
	var calls []struct {
		Ctx     context.Context
		Options rpc.StartSSHServerOptions
	}
	mock.lockStartSSHServerWithOptions.RLock()
	calls = mock.calls.StartSSHServerWithOptions
	mock.lockStartSSHServerWithOptions.RUnlock()
	return calls
}
