// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package grpctunnel

import (
	"context"
	"github.com/cli/cli/v2/internal/codespaces/api"
	"net/http"
	"sync"
)

// Ensure, that clientMock does implement client.
// If this is not the case, regenerate this file with moq.
var _ client = &clientMock{}

// clientMock is a mock implementation of client.
//
//	func TestSomethingThatUsesclient(t *testing.T) {
//
//		// make and configure a mocked client
//		mockedclient := &clientMock{
//			GetCodespaceFunc: func(ctx context.Context, name string, includeConnection bool) (*api.Codespace, error) {
//				panic("mock out the GetCodespace method")
//			},
//			HTTPClientFunc: func() (*http.Client, error) {
//				panic("mock out the HTTPClient method")
//			},
//			StartCodespaceFunc: func(ctx context.Context, name string) error {
//				panic("mock out the StartCodespace method")
//			},
//		}
//
//		// use mockedclient in code that requires client
//		// and then make assertions.
//
//	}
type clientMock struct {
	// GetCodespaceFunc mocks the GetCodespace method.
	GetCodespaceFunc func(ctx context.Context, name string, includeConnection bool) (*api.Codespace, error)

	// HTTPClientFunc mocks the HTTPClient method.
	HTTPClientFunc func() (*http.Client, error)

	// StartCodespaceFunc mocks the StartCodespace method.
	StartCodespaceFunc func(ctx context.Context, name string) error

	// calls tracks calls to the methods.
	calls struct {
		// GetCodespace holds details about calls to the GetCodespace method.
		GetCodespace []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// IncludeConnection is the includeConnection argument value.
			IncludeConnection bool
		}
		// HTTPClient holds details about calls to the HTTPClient method.
		HTTPClient []struct {
		}
		// StartCodespace holds details about calls to the StartCodespace method.
		StartCodespace []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
	}
	lockGetCodespace   sync.RWMutex
	lockHTTPClient     sync.RWMutex
	lockStartCodespace sync.RWMutex
}

// GetCodespace calls GetCodespaceFunc.
func (mock *clientMock) GetCodespace(ctx context.Context, name string, includeConnection bool) (*api.Codespace, error) {
	if mock.GetCodespaceFunc == nil {
		panic("clientMock.GetCodespaceFunc: method is nil but client.GetCodespace was just called")
	}
	callInfo := struct {
		Ctx               context.Context
		Name              string
		IncludeConnection bool
	}{
		Ctx:               ctx,
		Name:              name,
		IncludeConnection: includeConnection,
	}
	mock.lockGetCodespace.Lock()
	mock.calls.GetCodespace = append(mock.calls.GetCodespace, callInfo)
	mock.lockGetCodespace.Unlock()
	return mock.GetCodespaceFunc(ctx, name, includeConnection)
}

// GetCodespaceCalls gets all the calls that were made to GetCodespace.
// Check the length with:
//
//	len(mockedclient.GetCodespaceCalls())
func (mock *clientMock) GetCodespaceCalls() []struct {
	Ctx               context.Context
	Name              string
	IncludeConnection bool
} {
	var calls []struct {
		Ctx               context.Context
		Name              string
		IncludeConnection bool
	}
	mock.lockGetCodespace.RLock()
	calls = mock.calls.GetCodespace
	mock.lockGetCodespace.RUnlock()
	return calls
}

// HTTPClient calls HTTPClientFunc.
func (mock *clientMock) HTTPClient() (*http.Client, error) {
	if mock.HTTPClientFunc == nil {
		panic("clientMock.HTTPClientFunc: method is nil but client.HTTPClient was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHTTPClient.Lock()
	mock.calls.HTTPClient = append(mock.calls.HTTPClient, callInfo)
	mock.lockHTTPClient.Unlock()
	return mock.HTTPClientFunc()
}

// HTTPClientCalls gets all the calls that were made to HTTPClient.
// Check the length with:
//
//	len(mockedclient.HTTPClientCalls())
func (mock *clientMock) HTTPClientCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHTTPClient.RLock()
	calls = mock.calls.HTTPClient
	mock.lockHTTPClient.RUnlock()
	return calls
}

// StartCodespace calls StartCodespaceFunc.
func (mock *clientMock) StartCodespace(ctx context.Context, name string) error {
	if mock.StartCodespaceFunc == nil {
		panic("clientMock.StartCodespaceFunc: method is nil but client.StartCodespace was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockStartCodespace.Lock()
	mock.calls.StartCodespace = append(mock.calls.StartCodespace, callInfo)
	mock.lockStartCodespace.Unlock()
	return mock.StartCodespaceFunc(ctx, name)
}

// StartCodespaceCalls gets all the calls that were made to StartCodespace.
// Check the length with:
//
//	len(mockedclient.StartCodespaceCalls())
func (mock *clientMock) StartCodespaceCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockStartCodespace.RLock()
	calls = mock.calls.StartCodespace
	mock.lockStartCodespace.RUnlock()
	return calls
}
