// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package create

import (
	"io"
	"sync"
)

// Ensure, that gitClientMock does implement gitClient.
// If this is not the case, regenerate this file with moq.
var _ gitClient = &gitClientMock{}

// gitClientMock is a mock implementation of gitClient.
//
// 	func TestSomethingThatUsesgitClient(t *testing.T) {
//
// 		// make and configure a mocked gitClient
// 		mockedgitClient := &gitClientMock{
// 			PushFunc: func(args []string, stdout io.Writer, stderr io.Writer) error {
// 				panic("mock out the Push method")
// 			},
// 		}
//
// 		// use mockedgitClient in code that requires gitClient
// 		// and then make assertions.
//
// 	}
type gitClientMock struct {
	// PushFunc mocks the Push method.
	PushFunc func(args []string, stdout io.Writer, stderr io.Writer) error

	// calls tracks calls to the methods.
	calls struct {
		// Push holds details about calls to the Push method.
		Push []struct {
			// Args is the args argument value.
			Args []string
			// Stdout is the stdout argument value.
			Stdout io.Writer
			// Stderr is the stderr argument value.
			Stderr io.Writer
		}
	}
	lockPush sync.RWMutex
}

// Push calls PushFunc.
func (mock *gitClientMock) Push(args []string, stdout io.Writer, stderr io.Writer) error {
	if mock.PushFunc == nil {
		panic("gitClientMock.PushFunc: method is nil but gitClient.Push was just called")
	}
	callInfo := struct {
		Args   []string
		Stdout io.Writer
		Stderr io.Writer
	}{
		Args:   args,
		Stdout: stdout,
		Stderr: stderr,
	}
	mock.lockPush.Lock()
	mock.calls.Push = append(mock.calls.Push, callInfo)
	mock.lockPush.Unlock()
	return mock.PushFunc(args, stdout, stderr)
}

// PushCalls gets all the calls that were made to Push.
// Check the length with:
//     len(mockedgitClient.PushCalls())
func (mock *gitClientMock) PushCalls() []struct {
	Args   []string
	Stdout io.Writer
	Stderr io.Writer
} {
	var calls []struct {
		Args   []string
		Stdout io.Writer
		Stderr io.Writer
	}
	mock.lockPush.RLock()
	calls = mock.calls.Push
	mock.lockPush.RUnlock()
	return calls
}
