#!/bin/bash
set -e

current_tag="${GITHUB_REF#refs/tags/}"
start_ref="HEAD"

# Find the previous release on the same branch, skipping prereleases if the
# current tag is a full release
previous_tag=""
while [[ -z $previous_tag || ( $previous_tag == *-* && $current_tag != *-* ) ]]; do
  previous_tag="$(git describe --tags "$start_ref"^ --abbrev=0)"
  start_ref="$previous_tag"
done

git log "$previous_tag".. --reverse --first-parent --oneline | \
  while read -r sha title; do
    if [[ $title == "Merge pull request #"* ]]; then
      pr_num="$(grep -o '#[[:digit:]]\+' <<<"$title")"
      pr_desc="$(git show -s --format=%b "$sha" | sed -n '1,/^$/p' | tr $'\n' ' ')"
      printf "* %s %s\n\n" "$pr_desc" "$pr_num"
    else
      printf "* %s\n\n" "$title"
    fi
  done