package action

import (
	"github.com/rsteube/carapace"
)

// https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml
func ActionLanguages() carapace.Action {
	return carapace.ActionValuesDescribed(
		"1C Enterprise", "markup",
		"4D", "data",
		"ABAP", "programming",
		"ABAP CDS", "programming",
		"ABNF", "programming",
		"AGS Script", "programming",
		"AL", "programming",
		"AMPL", "programming",
		"ANTLR", "programming",
		"API Blueprint", "programming",
		"APL", "programming",
		"ASL", "markup",
		"ASN.1", "programming",
		"ASP.NET", "programming",
		"ATS", "data",
		"ActionScript", "markup",
		"Ada", "programming",
		"Adobe Font Metrics", "programming",
		"Agda", "data",
		"Alloy", "data",
		"Alpine Abuild", "programming",
		"Altium Designer", "data",
		"AngelScript", "markup",
		"Ant Build System", "programming",
		"ApacheConf", "programming",
		"Apex", "programming",
		"Apollo Guidance Computer", "programming",
		"AppleScript", "data",
		"Arc", "programming",
		"AsciiDoc", "programming",
		"AspectJ", "programming",
		"Assembly", "prose",
		"Asymptote", "programming",
		"Augeas", "programming",
		"AutoHotkey", "markup",
		"AutoIt", "programming",
		"Avro IDL", "programming",
		"Awk", "data",
		"Ballerina", "data",
		"Batchfile", "data",
		"Beef", "data",
		"Befunge", "data",
		"BibTeX", "programming",
		"Bison", "programming",
		"BitBake", "programming",
		"Blade", "programming",
		"BlitzBasic", "markup",
		"BlitzMax", "data",
		"Bluespec", "programming",
		"Boo", "programming",
		"Boogie", "programming",
		"Brainfuck", "programming",
		"Brightscript", "programming",
		"Browserslist", "programming",
		"C", "programming",
		"C#", "programming",
		"C++", "data",
		"C-ObjDump", "data",
		"C2hs Haskell", "programming",
		"CLIPS", "data",
		"CMake", "markup",
		"COBOL", "programming",
		"COLLADA", "programming",
		"CSON", "programming",
		"CSS", "programming",
		"CSV", "programming",
		"CWeb", "programming",
		"Cabal Config", "programming",
		"Cap'n Proto", "prose",
		"CartoCSS", "programming",
		"Ceylon", "prose",
		"Chapel", "programming",
		"Charity", "programming",
		"ChucK", "programming",
		"Cirru", "programming",
		"Clarion", "programming",
		"Classic ASP", "data",
		"Clean", "data",
		"Click", "programming",
		"Clojure", "programming",
		"Closure Templates", "programming",
		"Cloud Firestore Security Rules", "prose",
		"CoNLL-U", "programming",
		"CodeQL", "programming",
		"CoffeeScript", "data",
		"ColdFusion", "programming",
		"ColdFusion CFC", "programming",
		"Common Lisp", "programming",
		"Common Workflow Language", "programming",
		"Component Pascal", "programming",
		"Cool", "programming",
		"Coq", "programming",
		"Cpp-ObjDump", "data",
		"Creole", "data",
		"Crystal", "data",
		"Csound", "programming",
		"Csound Document", "programming",
		"Csound Score", "programming",
		"Cuda", "programming",
		"Cycript", "programming",
		"Cython", "markup",
		"D", "programming",
		"D-ObjDump", "programming",
		"DIGITAL Command Language", "programming",
		"DM", "programming",
		"DNS Zone", "programming",
		"DTrace", "data",
		"Dafny", "programming",
		"Darcs Patch", "programming",
		"Dart", "programming",
		"DataWeave", "data",
		"Dhall", "programming",
		"Diff", "data",
		"DirectX 3D File", "programming",
		"Dockerfile", "programming",
		"Dogescript", "data",
		"Dylan", "data",
		"E", "programming",
		"EBNF", "programming",
		"ECL", "programming",
		"ECLiPSe", "data",
		"EJS", "data",
		"EML", "programming",
		"EQ", "programming",
		"Eagle", "programming",
		"Easybuild", "programming",
		"Ecere Projects", "programming",
		"EditorConfig", "programming",
		"Edje Data Collection", "programming",
		"Eiffel", "programming",
		"Elixir", "programming",
		"Elm", "programming",
		"Emacs Lisp", "markup",
		"EmberScript", "programming",
		"Erlang", "programming",
		"F#", "markup",
		"F*", "programming",
		"FIGlet Font", "markup",
		"FLUX", "programming",
		"Factor", "data",
		"Fancy", "programming",
		"Fantom", "programming",
		"Faust", "programming",
		"Filebench WML", "data",
		"Filterscript", "programming",
		"Formatted", "programming",
		"Forth", "programming",
		"Fortran", "programming",
		"Fortran Free Form", "data",
		"FreeMarker", "data",
		"Frege", "data",
		"Futhark", "programming",
		"G-code", "programming",
		"GAML", "programming",
		"GAMS", "programming",
		"GAP", "programming",
		"GCC Machine Description", "programming",
		"GDB", "programming",
		"GDScript", "programming",
		"GEDCOM", "programming",
		"GLSL", "programming",
		"GN", "prose",
		"Game Maker Language", "programming",
		"Genie", "prose",
		"Genshi", "programming",
		"Gentoo Ebuild", "programming",
		"Gentoo Eclass", "programming",
		"Gerber Image", "data",
		"Gettext Catalog", "programming",
		"Gherkin", "programming",
		"Git Attributes", "programming",
		"Git Config", "programming",
		"Glyph", "programming",
		"Glyph Bitmap Distribution Format", "programming",
		"Gnuplot", "programming",
		"Go", "programming",
		"Golo", "data",
		"Gosu", "programming",
		"Grace", "programming",
		"Gradle", "programming",
		"Grammatical Framework", "programming",
		"Graph Modeling Language", "data",
		"GraphQL", "programming",
		"Graphviz (DOT)", "data",
		"Groovy", "programming",
		"Groovy Server Pages", "programming",
		"HAProxy", "programming",
		"HCL", "prose",
		"HLSL", "programming",
		"HTML", "data",
		"HTML+Django", "programming",
		"HTML+ECR", "programming",
		"HTML+EEX", "programming",
		"HTML+ERB", "programming",
		"HTML+PHP", "programming",
		"HTML+Razor", "programming",
		"HTTP", "programming",
		"HXML", "data",
		"Hack", "programming",
		"Haml", "programming",
		"Handlebars", "programming",
		"Harbour", "programming",
		"Haskell", "programming",
		"Haxe", "data",
		"HiveQL", "programming",
		"HolyC", "programming",
		"Hy", "programming",
		"HyPhy", "data",
		"IDL", "programming",
		"IGOR Pro", "markup",
		"INI", "programming",
		"IRC log", "programming",
		"Idris", "programming",
		"Ignore List", "programming",
		"ImageJ Macro", "programming",
		"Inform 7", "programming",
		"Inno Setup", "programming",
		"Io", "programming",
		"Ioke", "programming",
		"Isabelle", "programming",
		"Isabelle ROOT", "data",
		"J", "programming",
		"JFlex", "programming",
		"JSON", "programming",
		"JSON with Comments", "programming",
		"JSON5", "programming",
		"JSONLD", "programming",
		"JSONiq", "programming",
		"Jasmin", "programming",
		"Java", "programming",
		"Java Properties", "programming",
		"Java Server Pages", "programming",
		"JavaScript", "programming",
		"JavaScript+ERB", "programming",
		"Jison", "programming",
		"Jison Lex", "data",
		"Jolie", "programming",
		"Jsonnet", "programming",
		"Julia", "data",
		"Jupyter Notebook", "markup",
		"KRL", "programming",
		"Kaitai Struct", "programming",
		"KiCad Layout", "prose",
		"KiCad Legacy Layout", "markup",
		"KiCad Schematic", "prose",
		"Kit", "programming",
		"Kotlin", "programming",
		"Kusto", "programming",
		"LFE", "programming",
		"LLVM", "data",
		"LOLCODE", "programming",
		"LSL", "programming",
		"LTspice Symbol", "programming",
		"LabVIEW", "markup",
		"Lark", "programming",
		"Lasso", "markup",
		"Latte", "programming",
		"Lean", "programming",
		"Less", "programming",
		"Lex", "data",
		"LilyPond", "programming",
		"Limbo", "programming",
		"Linker Script", "programming",
		"Linux Kernel Module", "markup",
		"Liquid", "programming",
		"Literate Agda", "programming",
		"Literate CoffeeScript", "programming",
		"Literate Haskell", "data",
		"LiveScript", "programming",
		"Logos", "programming",
		"Logtalk", "data",
		"LookML", "programming",
		"LoomScript", "data",
		"Lua", "programming",
		"M", "programming",
		"M4", "data",
		"M4Sugar", "programming",
		"MATLAB", "programming",
		"MAXScript", "programming",
		"MLIR", "programming",
		"MQL4", "programming",
		"MQL5", "programming",
		"MTML", "programming",
		"MUF", "programming",
		"Macaulay2", "programming",
		"Makefile", "programming",
		"Mako", "programming",
		"Markdown", "programming",
		"Marko", "data",
		"Mask", "data",
		"Mathematica", "programming",
		"Maven POM", "data",
		"Max", "programming",
		"MediaWiki", "programming",
		"Mercury", "programming",
		"Meson", "programming",
		"Metal", "data",
		"Microsoft Developer Studio Project", "programming",
		"MiniD", "programming",
		"Mirah", "programming",
		"Modelica", "data",
		"Modula-2", "programming",
		"Modula-3", "programming",
		"Module Management System", "programming",
		"Monkey", "programming",
		"Moocode", "programming",
		"MoonScript", "data",
		"Motorola 68K Assembly", "programming",
		"Muse", "markup",
		"Mustache", "data",
		"Myghty", "programming",
		"NASL", "programming",
		"NCL", "markup",
		"NEON", "programming",
		"NL", "programming",
		"NPM Config", "programming",
		"NSIS", "markup",
		"NWScript", "markup",
		"Nearley", "programming",
		"Nemerle", "programming",
		"NetLinx", "data",
		"NetLinx+ERB", "programming",
		"NetLogo", "programming",
		"NewLisp", "data",
		"Nextflow", "programming",
		"Nginx", "data",
		"Nim", "data",
		"Ninja", "data",
		"Nit", "markup",
		"Nix", "programming",
		"Nu", "programming",
		"NumPy", "programming",
		"Nunjucks", "programming",
		"OCaml", "programming",
		"ObjDump", "data",
		"Object Data Instance Notation", "programming",
		"ObjectScript", "programming",
		"Objective-C", "programming",
		"Objective-C++", "programming",
		"Objective-J", "data",
		"Odin", "programming",
		"Omgrofl", "programming",
		"Opa", "programming",
		"Opal", "programming",
		"Open Policy Agent", "programming",
		"OpenCL", "programming",
		"OpenEdge ABL", "data",
		"OpenQASM", "programming",
		"OpenRC runscript", "markup",
		"OpenSCAD", "programming",
		"OpenStep Property List", "data",
		"OpenType Feature File", "programming",
		"Org", "programming",
		"Ox", "programming",
		"Oxygene", "programming",
		"Oz", "programming",
		"P4", "programming",
		"PHP", "programming",
		"PLSQL", "programming",
		"PLpgSQL", "programming",
		"POV-Ray SDL", "data",
		"Pan", "programming",
		"Papyrus", "programming",
		"Parrot", "programming",
		"Parrot Assembly", "markup",
		"Parrot Internal Representation", "programming",
		"Pascal", "data",
		"Pawn", "data",
		"Pep8", "markup",
		"Perl", "data",
		"Pic", "data",
		"Pickle", "markup",
		"PicoLisp", "data",
		"PigLatin", "programming",
		"Pike", "programming",
		"PlantUML", "data",
		"Pod", "data",
		"Pod 6", "programming",
		"PogoScript", "markup",
		"Pony", "programming",
		"PostCSS", "data",
		"PostScript", "data",
		"PowerBuilder", "programming",
		"PowerShell", "markup",
		"Prisma", "data",
		"Processing", "programming",
		"Proguard", "markup",
		"Prolog", "data",
		"Propeller Spin", "programming",
		"Protocol Buffer", "data",
		"Public Key", "programming",
		"Pug", "programming",
		"Puppet", "programming",
		"Pure Data", "data",
		"PureBasic", "programming",
		"PureScript", "prose",
		"Python", "programming",
		"Python console", "programming",
		"Python traceback", "programming",
		"Q#", "markup",
		"QML", "programming",
		"QMake", "programming",
		"Qt Script", "programming",
		"Quake", "programming",
		"R", "markup",
		"RAML", "programming",
		"RDoc", "data",
		"REALbasic", "programming",
		"REXX", "programming",
		"RMarkdown", "programming",
		"RPC", "programming",
		"RPM Spec", "data",
		"RUNOFF", "data",
		"Racket", "programming",
		"Ragel", "data",
		"Raku", "programming",
		"Rascal", "programming",
		"Raw token data", "programming",
		"ReScript", "data",
		"Readline Config", "programming",
		"Reason", "programming",
		"Rebol", "data",
		"Record Jar", "data",
		"Red", "programming",
		"Redcode", "programming",
		"Regular Expression", "programming",
		"Ren'Py", "programming",
		"RenderScript", "programming",
		"Rich Text Format", "programming",
		"Ring", "programming",
		"Riot", "markup",
		"RobotFramework", "data",
		"Roff", "data",
		"Roff Manpage", "programming",
		"Rouge", "programming",
		"Ruby", "data",
		"Rust", "programming",
		"SAS", "programming",
		"SCSS", "markup",
		"SMT", "programming",
		"SPARQL", "data",
		"SQF", "programming",
		"SQL", "programming",
		"SQLPL", "programming",
		"SRecode Template", "programming",
		"SSH Config", "programming",
		"STON", "programming",
		"SVG", "programming",
		"SWIG", "programming",
		"Sage", "data",
		"SaltStack", "markup",
		"Sass", "programming",
		"Scala", "markup",
		"Scaml", "programming",
		"Scheme", "prose",
		"Scilab", "programming",
		"Self", "programming",
		"ShaderLab", "programming",
		"Shell", "programming",
		"ShellSession", "programming",
		"Shen", "programming",
		"Sieve", "programming",
		"Slash", "programming",
		"Slice", "markup",
		"Slim", "programming",
		"SmPL", "programming",
		"Smali", "programming",
		"Smalltalk", "programming",
		"Smarty", "markup",
		"Solidity", "programming",
		"SourcePawn", "programming",
		"Spline Font Database", "programming",
		"Squirrel", "markup",
		"Stan", "programming",
		"Standard ML", "prose",
		"Starlark", "programming",
		"Stata", "programming",
		"Stylus", "prose",
		"SubRip Text", "programming",
		"SugarSS", "programming",
		"SuperCollider", "programming",
		"Svelte", "programming",
		"Swift", "data",
		"SystemVerilog", "programming",
		"TI Program", "programming",
		"TLA", "markup",
		"TOML", "programming",
		"TSQL", "programming",
		"TSV", "data",
		"TSX", "programming",
		"TXL", "programming",
		"Tcl", "programming",
		"Tcsh", "data",
		"TeX", "programming",
		"Tea", "programming",
		"Terra", "programming",
		"Texinfo", "programming",
		"Text", "programming",
		"Textile", "programming",
		"Thrift", "programming",
		"Turing", "programming",
		"Turtle", "programming",
		"Twig", "data",
		"Type Language", "programming",
		"TypeScript", "programming",
		"Unified Parallel C", "programming",
		"Unity3D Asset", "programming",
		"Unix Assembly", "programming",
		"Uno", "programming",
		"UnrealScript", "data",
		"UrWeb", "programming",
		"V", "programming",
		"VBA", "programming",
		"VBScript", "markup",
		"VCL", "programming",
		"VHDL", "data",
		"Vala", "programming",
		"Verilog", "programming",
		"Vim Help File", "data",
		"Vim Snippet", "data",
		"Vim script", "programming",
		"Visual Basic .NET", "data",
		"Volt", "programming",
		"Vue", "programming",
		"Wavefront Material", "programming",
		"Wavefront Object", "markup",
		"Web Ontology Language", "programming",
		"WebAssembly", "programming",
		"WebIDL", "programming",
		"WebVTT", "programming",
		"Wget Config", "programming",
		"Windows Registry Entries", "programming",
		"Wollok", "programming",
		"World of Warcraft Addon Data", "programming",
		"X BitMap", "programming",
		"X Font Directory Index", "programming",
		"X PixMap", "programming",
		"X10", "data",
		"XC", "programming",
		"XCompose", "data",
		"XML", "programming",
		"XML Property List", "programming",
		"XPages", "prose",
		"XProc", "programming",
		"XQuery", "programming",
		"XS", "programming",
		"XSLT", "data",
		"Xojo", "programming",
		"Xtend", "programming",
		"YAML", "programming",
		"YANG", "programming",
		"YARA", "programming",
		"YASnippet", "data",
		"Yacc", "programming",
		"ZAP", "markup",
		"ZIL", "data",
		"Zeek", "markup",
		"ZenScript", "markup",
		"Zephir", "data",
		"Zig", "programming",
		"Zimpl", "prose",
		"cURL Config", "markup",
		"desktop", "prose",
		"dircolors", "data",
		"eC", "markup",
		"edn", "data",
		"fish", "programming",
		"mIRC Script", "markup",
		"mcfunction", "data",
		"mupad", "markup",
		"nanorc", "data",
		"nesC", "programming",
		"ooc", "data",
		"q", "data",
		"reStructuredText", "data",
		"sed", "data",
		"wdl", "programming",
		"wisp", "data",
		"xBase", "markup",
	)
}
