// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// GitClient is an autogenerated mock type for the gitClient type
type GitClient struct {
	mock.Mock
}

// Push provides a mock function with given fields: args, stdout, stderr
func (_m *GitClient) Push(args []string, stdout io.Writer, stderr io.Writer) error {
	ret := _m.Called(args, stdout, stderr)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, io.Writer, io.Writer) error); ok {
		r0 = rf(args, stdout, stderr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
