name: Bump Go
on:
  schedule:
    - cron: "0 3 * * *" # 3 AM UTC
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  bump-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: 'go.mod'

      - name: Bump Go version
        env:
          GIT_COMMITTER_NAME: cli automation
          GIT_AUTHOR_NAME: cli automation
          GIT_COMMITTER_EMAIL: noreply@github.com
          GIT_AUTHOR_EMAIL: noreply@github.com
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash .github/workflows/scripts/bump-go.sh --apply go.mod
