name: Bump Go
on:
  schedule:
    - cron: "0 3 * * *" # 3 AM UTC
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  bump-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 'stable'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.13.2
          install-only: true

      - name: Bump Go version
        env:
          GIT_COMMITTER_NAME: cli automation
          GIT_AUTHOR_NAME: cli automation
          GIT_COMMITTER_EMAIL: noreply@github.com
          GIT_AUTHOR_EMAIL: noreply@github.com
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash .github/workflows/scripts/bump-go.sh --apply go.mod
