name: Unit and Integration Tests
on:
  push:
    branches:
      - trunk
  pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-firewall, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"

      - name: Download dependencies
        run: go mod download

      - name: Run unit and integration tests
        run: go test -race -tags=integration ./...

      - name: Build
        run: go build -v ./cmd/gh

  integration-tests:
    env:
      GH_TOKEN: ${{ github.token }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-firewall, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"

      - name: Build executable
        run: make

      - name: Run attestation command set integration tests
        shell: bash
        run: |
          ./test/integration/attestation-cmd/run-all-tests.sh "${{ matrix.os }}"
